In [276]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay

In [278]:
data = pd.read_csv('CarPrice_Assignment.csv')
data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [280]:
data = data[['fueltype', 'carbody', 'drivewheel', 'enginesize', 'horsepower', 'price', 'citympg','CarName']]

In [282]:
data.head()

fueltype      carbody drivewheel  enginesize  horsepower    price  citympg  \
0      gas  convertible        rwd         130         111  13495.0       21   
1      gas  convertible        rwd         130         111  16500.0       21   
2      gas    hatchback        rwd         152         154  16500.0       19   
3      gas        sedan        fwd         109         102  13950.0       24   
4      gas        sedan        4wd         136         115  17450.0       18   

                    CarName  
0        alfa-romero giulia  
1       alfa-romero stelvio  
2  alfa-romero Quadrifoglio  
3               audi 100 ls  
4                audi 100ls

In [284]:
data['fueltype'].unique()

array(['gas', 'diesel'], dtype=object)

In [286]:
data['carbody'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [288]:
data['drivewheel'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [290]:
data_num = data.select_dtypes(['number'])

In [292]:
data_num.head()

enginesize  horsepower    price  citympg
0         130         111  13495.0       21
1         130         111  16500.0       21
2         152         154  16500.0       19
3         109         102  13950.0       24
4         136         115  17450.0       18

In [294]:
data_cat = data.select_dtypes(['object'])

In [296]:
data_cat = data_cat.drop('CarName',axis=1)
data_cat.head()

fueltype      carbody drivewheel
0      gas  convertible        rwd
1      gas  convertible        rwd
2      gas    hatchback        rwd
3      gas        sedan        fwd
4      gas        sedan        4wd

In [298]:
from sklearn.preprocessing import MinMaxScaler

In [300]:
scale = MinMaxScaler()

In [302]:
for col in data_num:
    scale.fit_transform(data_num[[col]])
    data_num[col] = scale.transform(data_num[[col]])

In [304]:
data_num.head()

enginesize  horsepower     price   citympg
0    0.260377    0.262500  0.207959  0.222222
1    0.260377    0.262500  0.282558  0.222222
2    0.343396    0.441667  0.282558  0.166667
3    0.181132    0.225000  0.219254  0.305556
4    0.283019    0.279167  0.306142  0.138889

In [306]:
from sklearn.preprocessing import LabelEncoder

In [308]:
l = LabelEncoder()

In [311]:
for col in data_cat:
    data_cat[col] = l.fit_transform(data_cat[col])

In [313]:
data_cat.head()

fueltype  carbody  drivewheel
0         1        0           2
1         1        0           2
2         1        2           2
3         1        3           1
4         1        3           0

In [315]:
data_cat['fueltype'].unique() # ['gas', 'diesel']

array([1, 0])

In [317]:
data_cat['carbody'].unique() # ['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop']

array([0, 2, 3, 4, 1])

In [319]:
data_cat['drivewheel'].unique() # ['rwd', 'fwd', '4wd']

array([2, 1, 0])

In [321]:
new_data = pd.concat([data_num , data_cat] , axis=1)

In [323]:
new_data

enginesize  horsepower     price   citympg  fueltype  carbody  drivewheel
0      0.260377    0.262500  0.207959  0.222222         1        0           2
1      0.260377    0.262500  0.282558  0.222222         1        0           2
2      0.343396    0.441667  0.282558  0.166667         1        2           2
3      0.181132    0.225000  0.219254  0.305556         1        3           1
4      0.283019    0.279167  0.306142  0.138889         1        3           0
..          ...         ...       ...       ...       ...      ...         ...
200    0.301887    0.275000  0.291123  0.277778         1        3           2
201    0.301887    0.466667  0.345738  0.166667         1        3           2
202    0.422642    0.358333  0.406311  0.138889         1        3           2
203    0.316981    0.241667  0.430763  0.361111         0        3           2
204    0.301887    0.275000  0.434611  0.166667         1        3           2

[205 rows x 7 columns]

In [325]:
new_data['fueltype'].unique()

array([1, 0])

In [327]:
x = new_data

In [415]:
y = data.CarName

In [417]:
y.head()

0          alfa-romero giulia
1         alfa-romero stelvio
2    alfa-romero Quadrifoglio
3                 audi 100 ls
4                  audi 100ls
Name: CarName, dtype: object

In [419]:
label = LabelEncoder()
y = label.fit_transform(y)

In [421]:
y

array([  2,   3,   1,   4,   5,   9,   5,   7,   6,   8,  10,  10,  11,
        12,  15,  13,  14,  12,  24,  25,  26,  35,  27,  32,  34,  29,
        28,  30,  33,  31,  39,  43,  39,  37,  43,  38,  42,  36,  41,
        44,  36,  39,  40,  47,  45,  46,  45,  49,  48,  50,  52,  51,
        61,  59,  58,  53,  54,  60,  55,  53,  57,  56,  59,  58,  53,
        54,  60,  19,  17,  16,  22,  20,  23,  18,  21,  62,  65,  64,
        68,  63,  66,  63,  68,  63,  66,  67,  69,  68,  66,   0,  73,
        81,  76,  83,  77,  74,  76,  78,  70,  81,  79,  71,  72,  80,
        82,  75,  70,  85,  84,  86,  85,  85,  88,  85,  87,  85,  85,
        88,  92,  89,  92,  93,  91,  94,  90,  98,  95,  97,  96,  97,
        99, 100, 101, 103, 103, 102, 102, 101, 104, 107, 107, 104, 106,
       105, 108, 109, 110, 111, 107, 107, 123, 120, 116, 121, 117, 112,
       125, 116, 120, 115, 120, 115, 125, 118, 120, 114, 119, 122, 115,
       126, 127, 115, 124, 115, 113, 120, 115, 125, 118, 120, 12

In [455]:
# original = label.inverse_transform(y)
# original

In [425]:
from sklearn.model_selection import train_test_split

In [427]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=42)

In [429]:
ytrain

array([125,  62, 113,  43,  11,  38,  98,  40, 125, 102, 107,  51,  85,
       119,  39,  90,  68,  89,  28, 101, 139,  88,   1,  64,  45,  91,
        97,  67, 104,  42,  87,  56,  27, 102, 135,  37,  10, 144, 118,
         5,  30,  95, 140, 104,   5,  39,  86, 136,  85, 107,  10,  59,
        92, 123, 127,   2, 133, 130,  22, 142,  53,  45, 114,  33,  36,
        84,  94,  32, 112, 145,  63,  44, 124,  49,  77, 120,  47, 106,
         4,  75,  59, 103, 137, 115, 146,  50,  66,  43,   7,  85,  81,
        63, 128, 131,   0,   6,  12,  53, 115, 100,  12,  23, 126, 103,
       115, 143,  58,  58,  85,  52, 138, 126,  55,  48,  66,  35,  60,
       120, 141,  97,  36, 116, 132,   3,  61, 107,  99, 120,  80,  81,
        85,  68,  21,  93, 143,  26, 132,  20,  70,  15,  76, 120,  72])

In [431]:
from sklearn.neighbors import KNeighborsClassifier

In [433]:
best_accuracy = 0
best_k = 1
for k in range(1, 21):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(xtrain, ytrain)
    ypred = knn.predict(xtest)
    acc = accuracy_score(ytest, ypred)
    if acc > best_accuracy:
        best_accuracy = acc
        best_k = k

In [435]:
best_k

1

In [437]:
model = KNeighborsClassifier(n_neighbors=best_k)

In [439]:
model.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=1)

In [441]:
ypred= model.predict(xtrain)

In [443]:
model.score(xtrain,ytrain)

0.972027972027972

In [477]:
accuracy_score(ytrain,ypred)

0.972027972027972

In [479]:
predicted_car=  model.predict([[0.260377, 0.262500	,0.282558	,0.222222,	1,	0	,2]])

C:\Users\somna\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [481]:
predicted_label = predicted_car[0]  # extract the number 145
car_name = label.inverse_transform([predicted_label])[0]
car_name

'alfa-romero stelvio'